### ISSUE TITLE
Missing background/font colors

### ISSUE THREAD

**Issue by felixsanz** [juliancoleman/ramda-syntax#10]
Looks like now it's missing those.

In syntax-variables file you can see `syntax-background-color` and `syntax-text-color`, but they are not used anywhere

**Comment by juliancoleman** [comment]
I think I did away with this file. The syntax theme itself depends on this file, otherwise there will be errors. I don't think I'm using anything from this file. But I'll have to doublecheck

**Comment by felixsanz** [comment]
You're missing those colors. Check editor.less, it's almost empty. It lacks of lot of selectors. Check atom's one-dark theme to get some help
