### ISSUE TITLE
Deprecated selector in `ramda-syntax\index.less`

### ISSUE THREAD

**Issue by ethnerom** [juliancoleman/ramda-syntax#11]
In `ramda-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `ul[is='atom-tabs'] *:not('.tab.active') li[is='tabs-tab'].active .title` => `ul[is='atom-tabs'] *:not('.tab.active') li[is='tabs-tab'].active .syntax--title`

* `.tab-bar .tab .title` => `.tab-bar .syntax--tab .syntax--title`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by juliancoleman** [comment]
Thanks. This is a known issue #8
