### ISSUE TITLE
Why purple tabs?

### ISSUE THREAD

**Issue by ghost** [juliancoleman/ramda-syntax#12]
I thought this is a syntax theme? Why does it coloring my UI?

**Comment by juliancoleman** [comment]
I thought I'd do something similar to the repl by completely colouring the editor itself. It turns out it doesn't play with the UI very well, so I'm going to just take that out on Wednesday when I have some free time to write the next release.

**Comment by ghost** [comment]
Thanks. I suggest you create a new ui-theme, name it ramda-ui and use your purple ui hacks there ;-)
I prefer simple dark colors but I'm sure some will like it.

**Comment by criduvero** [comment]
Completely in agreement with @dotmagic. I love the dark colors
