### ISSUE TITLE
Incorrect comment colors

### ISSUE THREAD

**Issue by ntwcklng** [juliancoleman/ramda-syntax#19]
Hey Julian,

the colors for the comments in js files are incorrect i think:
![screenshot at mai 06 08-52-35](https://cloud.githubusercontent.com/assets/8714775/25770597/85ffa076-3239-11e7-98ae-693922ccf847.png)

Atom: 1.16.0
Ramda-Syntax: 1.0.3

**Comment by juliancoleman** [comment]
I'll get this fixed up by the end of this week!

**Comment by ntwcklng** [comment]
@juliancoleman would you mind if i tackle this?

**Comment by juliancoleman** [comment]
I would not be upset about that. Please do! I'll review your PR when you're done.
