### ISSUE TITLE
Looks like ass on atom 1.14

### ISSUE THREAD

**Issue by juliancoleman** [juliancoleman/ramda-syntax#5]
* `const` isn't coloured
* object properties and methods should be `blue`
* tabs look stupid on some themes
* xml and php aren't supported
* tabs still look stupid on some themes
...

Will come up with more as I find them.

**Comment by Larandar** [comment]
Also:
![2017-01-23 Screenshot](https://cloud.githubusercontent.com/assets/906021/22201495/29fd9af6-e164-11e6-8965-04d76eb696dc.png)

- HTML, PHP and any XML based syntax doesn't work.
- Tabs are now pink-ish

**Comment by juliancoleman** [comment]
HTML should be working now if you've downloaded the latest update. I will work on XML, and maybe PHP. But I should warn you that I have a heavy bias against PHP. However, I know the developer community is large, so I will show support. It's just kinda on the back burner. Also, the tabs should be pinkish. The header bar from the [repl](ramdajs.org/repl/) is actually pink, and the currently active link is just a shade darker. I didn't want to make a UI, but bring some ramda-esque aesthetics into the editor. But I should note that it is able to be disabled.

**Comment by WA9ACE** [comment]
There's an issue with the pink tabs in several themes, including the defaults such as Atom Dark.

Here's an example.
![glitch](https://cloud.githubusercontent.com/assets/925716/22253238/d25500e4-e21e-11e6-82b4-da5788b51152.png)

I can separate this out into a different issue if preferred.

**Comment by juliancoleman** [comment]
I am aware of the issue of the tabs looking funky with certain themes. I thought I had resolved the one for `atom-dark`, but I guess this is still present for most users. I'll go ahead and reinvestigate this issue after work. I appreciate you including an image, as well as using `React`! :shipit:

**Comment by amandaporto** [comment]
Also, this syntax used to work fine with scss, but now everything is white. Only works with less and css.

Edit: Adding here that JSX syntax is also broken now.

**Comment by WA9ACE** [comment]
I didn't realize that's what it was. I was poking at atom trying to figure out why my sass package wasn't working.

**Comment by juliancoleman** [comment]
@amandaporto @C0deMaver1ck loving the feedback, guys. I appreciate the contributions. I'll get these squared away and release an update! Or if y'all would like to open a new issue and paralleled PR to it, that'd be awesome, too. The more help I can get, the faster I can roll these updates out :heart:

**Comment by WA9ACE** [comment]
I've never worked on an atom package before, but now seems as good a time as ever! I'll see if I can send a PR in the next few days or so.

**Comment by juliancoleman** [comment]
@C0deMaver1ck epic! thanks! and if the code looks dirty, refactoring to your liking is acceptable.

**Comment by Larandar** [comment]
There is something strange about that, a syntax should be mostly agnostic of the language.
But I just opened a Java file and only comments are highlighted.

**Comment by juliancoleman** [comment]
Yeah, comments are agnostic hahaha @Larandar I've been rethinking the way that I've scaffolded this. I was trying to take a TJ Holowaychuk approach to how he makes his packages, and I've failed quite miserably at the end of the day. My initial reasoning for doing it language-specific was because if you install a package, like `atom-beautify` for example, the colours and classes might be different than just `language-javascript`. I guess what I'm trying to say is that I'm overall unfamiliar with how packages are assigning classes. But what I can say is that a `meta` in JavaScript and a `meta` in Scala might need to be coloured differently for readability.

**Comment by bradpurchase** [comment]
<img width="603" alt="screenshot 2017-02-09 09 33 12" src="https://cloud.githubusercontent.com/assets/5716/22787593/d5afc9ac-eeaa-11e6-91d1-2afe405476d9.png">

Just adding this, looks like Ruby syntax highlighting is broken as well.

**Comment by juliancoleman** [comment]
@bradpurchase perfect. thank you so much

**Comment by amandaporto** [comment]
Any headway on this? 🤓

**Comment by juliancoleman** [comment]
@amandaporto yes, ma'am! I have a free weekend. I ended up rewriting the entire syntax theme, but I don't have it on branch yet. But I can say that XML and PHP support should be included in this one.

**Comment by juliancoleman** [comment]
@amandaporto sorry about the delay. New update is released! Please let me know if you have issues with it. If you do, please open up a new issue as I'l be closing this one since the issue is no longer relevant. Anyhow, I appreciate your patience. @bradpurchase, @C0deMaver1ck, and @Larandar as well. Thanks for your patience. Enjoy the new update!

**Comment by bradpurchase** [comment]
@juliancoleman looks amazing! I think I have my new favorite syntax theme 👍

**Comment by juliancoleman** [comment]
YESSSSSSSSSSSSSSS. Thank you!

**Comment by amandaporto** [comment]
Looks great, but it looks like you broke Github markdown syntax.

**Comment by juliancoleman** [comment]
I did. I have that and JSX coming in an update.

**Comment by juliancoleman** [comment]
It's hard to _ramda_-ify a language like MD

**Comment by juliancoleman** [comment]
Can you confirm that Markdown is all white?
