### ISSUE TITLE
The purple color

### ISSUE THREAD

**Issue by opalafox** [juliancoleman/ramda-syntax#6]
i just download the update and the color of my tabs looks very rare!

**Comment by juliancoleman** [comment]
Hi, @opalafox. Could you upload a screenshot for me?

**Comment by opalafox** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/23559892/21947258/efd425b4-d9a9-11e6-8a57-0a13663a1ebb.png)

**Comment by juliancoleman** [comment]
Ah, that should not be happening. It seems to be an issue with One Dark overriding my styles. I'll look into this tonight unless you'd like to take a stab at resolving this and opening a PR.

**Comment by opalafox** [comment]
Yes! , 1.13.0

2017-01-13 16:13 GMT-06:00 J. Coleman <notifications@github.com>:

**Comment by opalafox** [comment]
can i back to the previous version?

2017-01-13 16:17 GMT-06:00 Octavio Alberto Palafox Valdez <
opalafox@anzen.com.mx>:

**Comment by juliancoleman** [comment]
You can try rolling back. Simply download the release from `atom/atom` and then build the app. If you can hold out for a couple hours, I can attempt to roll out an update for this so that you can stay on 1.13

**Comment by opalafox** [comment]
Great! , thank you! ill be waiting (Y)

2017-01-13 16:33 GMT-06:00 J. Coleman <notifications@github.com>:

**Comment by criduvero** [comment]
@juliancoleman I love your syntax color, but I hate the purple color on my tabs since last theme update. Can you please remove it? or can you please help me to remove the TAB purple color?
Thanks in advance

**Comment by opalafox** [comment]
Good morning!

Yes , please! , me too!





2017-01-16 11:29 GMT-06:00 Cristian Velásquez <notifications@github.com>:

**Comment by criduvero** [comment]
HTML colors are not working. I'm on Atom 1.13.0. Someone else. Thanks in advance.
![ramda](https://cloud.githubusercontent.com/assets/13077575/21994382/6d6a3c12-dbed-11e6-9ef7-0b346315369f.PNG)

**Comment by criduvero** [comment]
@opalafox  Last version working correctly 0.10.3: [DOWNLOAD](https://github.com/juliancoleman/ramda-syntax/archive/v0.10.3.zip)

**Comment by juliancoleman** [comment]
@criduvero I have not finished the html styles just yet. Also, I highly suggest your `breadcrumb` be generated by your view controller :+1: at any rate, I've been pretty stacked at work and haven't been able to work too much on this theme. Moreso, my time spent is often with Christ, but bear with me. I appreciate this theme as much as many do!

**Comment by juliancoleman** [comment]
Also, @criduvero , would you mind opening an issue for the HTML syntax highlighting? That way I can open a PR for it.

**Comment by criduvero** [comment]
@juliancoleman 1. Why you say "I highly suggest your breadcrumb be generated by your view controller"?. 
2. I'll create a new issue for HTML syntax color

**Comment by juliancoleman** [comment]
@criduvero right now, you have `<ol class="breadcrumb">` with a list-item of class `active`. If you dynamically create the breadcrumb with your view controller, you can use `$locationProvider`s `history` to dynamically create the breadcrumb and assign the `active` class where needed.

Thanks also for opening the issue! I'll get working on it now.

**Comment by juliancoleman** [comment]
@opalafox as of now, the tab issue is declared fixed. I'll go ahead and close this issue. Just update `ramda-syntax` in atom 1.13.0
