### ISSUE TITLE
HTML colors are not working. Atom 1.13.0

### ISSUE THREAD

**Issue by criduvero** [juliancoleman/ramda-syntax#7]
HTML colors are not working. I'm on Atom 1.13.0
![6d6a3c12-dbed-11e6-9ef7-0b346315369f](https://cloud.githubusercontent.com/assets/13077575/22030300/34183edc-dcab-11e6-9462-de15cb2b7264.PNG)

**Comment by juliancoleman** [comment]
This is also an issue for Atom 1.14 beta

**Comment by juliancoleman** [comment]
Fixed in 2fb9e9e. I am open to new colour schemes. But I would like to maintain a ramda-esque colour palette

**Comment by criduvero** [comment]
After updated to 0.12.0 I have the same error

**Comment by juliancoleman** [comment]
Let me take a look at what's going on with this one.

**Comment by juliancoleman** [comment]
@criduvero try closing Atom and opening again. I'm not experiencing this issue on Atom 1.13 or Atom Beta 1.14. Maybe all that has to happen is the styles need to be reloaded.

**Comment by criduvero** [comment]
@juliancoleman The same. I'm on Xubuntu x64 and Windows 7 x64. Issue #6 is still there.
![ramda2](https://cloud.githubusercontent.com/assets/13077575/22112920/af16b946-de32-11e6-93a2-ad291309ca4d.PNG)

**Comment by juliancoleman** [comment]
I'm thinking this could be an incompatibility with another package. I noticed the double-curlies are coloured green. They aren't green in the version of Atom I am using. Could you try disabling any Angular syntaxes and see if that fixes the issue?

**Comment by criduvero** [comment]
After disabling all packages and themes: angularjs 0.3.5 package is incompatible  with your theme. Last commit was on 2016-07-27. Your theme was working in december perfectly. I don't now if Atom new versions have changed the way it serves its CSS. In any case I can not work without that plugin. 
Issue #6 is still there, Elementary OS 0.4 Loki and W7 x64.
Ramda-syntax 0.10.3 version works perfectly Although the colors are not the same
![captura realizada el 2017-01-20 11 55 49](https://cloud.githubusercontent.com/assets/13077575/22157844/743f0f1e-df07-11e6-82e5-276b82fe9857.png)

**Comment by juliancoleman** [comment]
Atom changes the way CSS selectors are referenced. Any syntax-related theme must prefix selectors with `.syntax--`. On the topic of the tabs again, I'm not sure why they still look like that. I had already released an update to address this issue, but I am aware that Atom's `One Dark` theme overwrites a ton of styles. I may have to move the tabs to a ui-theme, but that'll have to be another day. Ramda itself does not have a presentable UI to work with, which is why I haven't made one.

**Comment by criduvero** [comment]
angularjs package has syntax highlighting, what is causing the issue in the color. I'm gonna put an issue in their repository

**Comment by juliancoleman** [comment]
Perfect. Thank you! I'll also try to support that package in some way as well.
