### ISSUE TITLE
Deprecated selector in `ramda-syntax/index.less`

### ISSUE THREAD

**Issue by charles-mutabazi** [juliancoleman/ramda-syntax#8]
In `ramda-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `ul[is='atom-tabs'] *:not('.tab.active') li[is='tabs-tab'].active .title` => `ul[is='atom-tabs'] *:not('.tab.active') li[is='tabs-tab'].active .syntax--title`

* `.tab-bar .tab .title` => `.tab-bar .syntax--tab .syntax--title`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by juliancoleman** [comment]
@charles-mutabazi thank you for this contribution! I'll get that sorted out ASAP.

**Comment by Freivincampbell** [comment]
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

ul[is='atom-tabs'] *:not('.tab.active') li[is='tabs-tab'].active .title => ul[is='atom-tabs'] *:not('.tab.active') li[is='tabs-tab'].active .syntax--title
.tab-bar .tab .title => .tab-bar .syntax--tab .syntax--title
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by juliancoleman** [comment]
I'm aware of this issue. I'm currently working on all of this as I'm typing this comment. I should have quite a few new updates for this theme today. So stay tuned! @Freivincampbell @charles-mutabazi

**Comment by Freivincampbell** [comment]
@juliancoleman thanks
