### ISSUE TITLE
No master branch

### ISSUE THREAD

**Issue by felixsanz** [juliancoleman/ramda-syntax#9]
There is no master branch, it was a mistake on the last release?

**Comment by juliancoleman** [comment]
There is currently no master branch for the reason that I have so many merge conflicts with each release. And because when I release a new version, I stop supporting older versions of Atom, so it means very little to me to keep around old code. That's all, really. But great observation! I'm generally against deleting the master branch

**Comment by felixsanz** [comment]
But thats why semver exists right? I think the best place to manage this kind of changes is the `version` key inside `package.json`. If your package contains breaking changes on every release thats fine! :P But its your decision ofc, im just suggesting. Thanks. Feel free to close this issue if you're done with it.

**Comment by juliancoleman** [comment]
Semver exists, but Github doesn't care about semver. I have a version key inside of my `package.json`, but the way that `git` handles changes based on branches, that was the only reason why. So when I would try to merge back into master, I would get an ass ton of merge conflicts, and I wanted to avoid that altogether. I wasn't actually expecting Atom to change the nature of how styles were applied. If this wasn't the case, I'd probably still have a master branch. I will probably end up redoing this entire syntax theme on the basis of global support first, and then fine-tuning later on. I've found it quite paralyzing to have language-specific styles. But I appreciate you, @felixsanz. Your suggestion has me thinking twice about how I've gone about this entire project. I just wish I wasn't the only one working on this. If I had one or two more people, I'd be able to get this up and running much quicker.

**Comment by juliancoleman** [comment]
I'm going to leave this open for my own reference.

**Comment by felixsanz** [comment]
This will reset the commit history on every release

**Comment by juliancoleman** [comment]
That's right. It's unfortunate, but I'm not so much concerned about backwards compatibility. I'm consistently thinking of ways to improve this development process, but it is literally just CSS.

**Comment by felixsanz** [comment]
Sorry but i just don't get it. There are dozens of syntax themes for atom and all of them uses `master`. Why this proyect can't? You're basically punishing updated users in favor of the deprecations. The theme is missing colors and looks awful in most contexts.

**Comment by juliancoleman** [comment]
The thing is that I don't need a branch with the name `master`. The current branch is the master branch, it's just called something different. Anyway, I'm sure there's a better way of doing this, but I'm a bit too busy to actually get around to updating this syntax theme. If you have a concern, please open a PR, reference this issue, and I'll gladly review the PR. I'm beyond open to public contributions. I literally cannot do this myself.

**Comment by juliancoleman** [comment]
If you can give me a week, I'll get back around to this. I have to meet a hard deadline at work and don't have much time for my freelance projects.

**Comment by felixsanz** [comment]
Sure! No demanding here! :+1: Thanks!
